# 
include ../Makefile.properties
export ISENSE_PATH=/home/amaxilatis/sdks/iSenseAll
#------------------------------------------------------------------------------
#-- TODO: Add your Source (.c/.cpp) files here
#------------------------------------------------------------------------------

TARGET = TelosBCollectorApp
SRC_PATH = src

BLDSRCS	= TelosBCollectorApp.cpp 
