# 
include ../Makefile.properties
#export ISENSE_PATH=/home/amaxilatis/sdks/iSenseAll
export ISENSE_PATH=/home/amaxilatis/sdks/iSenseTelosb

#------------------------------------------------------------------------------
#-- TODO: Add your Source (.c/.cpp) files here
#------------------------------------------------------------------------------

TARGET = TelosBCollectorApp
SRC_PATH = src

BLDSRCS	= TelosBCollectorApp.cpp 
