 #!/bin/bash 
### BEGIN INIT INFO 
# Provides:          autoReports
# Required-Start:      
# Required-Stop:       
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6 
# Short-Description: Start daemon at boot time 
# Description:       Enable service provided by daemon. 
### END INIT INFO 
name=autoReports
case $1 in 
"start") 

nohup /path.to.execute > /var/log/autoReports.log &
 
;;
*) 
	echo "use with start to start reporting"
esac 
